export const SET_USERS_LIST = 'SET_USERS_LIST';

export const SET_USER_PROFILE = 'SET_USER_PROFILE';

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export const TOGGLE_LOADED = 'TOGGLE_LOADED';
